// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversion_outputs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createConversionJobOutput = `-- name: CreateConversionJobOutput :one
INSERT INTO conversion_job_outputs (
    conversion_job_id,
    content_sha256,
    media_type
)
SELECT
    job.id,
    $1,
    $2
FROM conversion_jobs AS job
WHERE job.id = $3
  AND job.status = 'running'
RETURNING
    conversion_job_id,
    content_sha256,
    media_type,
    created_at
`

type CreateConversionJobOutputParams struct {
	ContentSha256   string
	MediaType       string
	ConversionJobID uuid.UUID
}

func (q *Queries) CreateConversionJobOutput(ctx context.Context, arg CreateConversionJobOutputParams) (ConversionJobOutput, error) {
	row := q.db.QueryRow(ctx, createConversionJobOutput, arg.ContentSha256, arg.MediaType, arg.ConversionJobID)
	var i ConversionJobOutput
	err := row.Scan(
		&i.ConversionJobID,
		&i.ContentSha256,
		&i.MediaType,
		&i.CreatedAt,
	)
	return i, err
}

const getConversionJobOutputByJobID = `-- name: GetConversionJobOutputByJobID :one
SELECT
    conversion_job_id,
    content_sha256,
    media_type,
    created_at
FROM conversion_job_outputs
WHERE conversion_job_id = $1
`

func (q *Queries) GetConversionJobOutputByJobID(ctx context.Context, conversionJobID uuid.UUID) (ConversionJobOutput, error) {
	row := q.db.QueryRow(ctx, getConversionJobOutputByJobID, conversionJobID)
	var i ConversionJobOutput
	err := row.Scan(
		&i.ConversionJobID,
		&i.ContentSha256,
		&i.MediaType,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestConversionJobOutputByProjectFile = `-- name: GetLatestConversionJobOutputByProjectFile :one
SELECT
    output.conversion_job_id,
    output.content_sha256,
    output.media_type,
    output.created_at
FROM conversion_job_outputs AS output
JOIN conversion_jobs AS job
  ON job.id = output.conversion_job_id
WHERE job.project_id = $1
  AND job.project_file_id = $2
  AND job.status = 'succeeded'
ORDER BY
    job.finished_at DESC,
    job.id DESC
LIMIT 1
`

type GetLatestConversionJobOutputByProjectFileParams struct {
	ProjectID     uuid.UUID
	ProjectFileID uuid.UUID
}

func (q *Queries) GetLatestConversionJobOutputByProjectFile(ctx context.Context, arg GetLatestConversionJobOutputByProjectFileParams) (ConversionJobOutput, error) {
	row := q.db.QueryRow(ctx, getLatestConversionJobOutputByProjectFile, arg.ProjectID, arg.ProjectFileID)
	var i ConversionJobOutput
	err := row.Scan(
		&i.ConversionJobID,
		&i.ContentSha256,
		&i.MediaType,
		&i.CreatedAt,
	)
	return i, err
}
