// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversion_jobs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const claimNextPendingConversionJob = `-- name: ClaimNextPendingConversionJob :one
WITH next_job AS (
    SELECT id
    FROM conversion_jobs
    WHERE status = 'pending'
    ORDER BY
        created_at ASC,
        id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE conversion_jobs AS job
SET
    status = 'running',
    attempt_count = job.attempt_count + 1,
    started_at = now(),
    finished_at = NULL,
    last_error = NULL,
    updated_at = now()
FROM next_job
WHERE job.id = next_job.id
RETURNING
    job.id,
    job.project_id,
    job.project_file_id,
    job.status,
    job.attempt_count,
    job.last_error,
    job.created_at,
    job.started_at,
    job.finished_at,
    job.updated_at
`

func (q *Queries) ClaimNextPendingConversionJob(ctx context.Context) (ConversionJob, error) {
	row := q.db.QueryRow(ctx, claimNextPendingConversionJob)
	var i ConversionJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectFileID,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConversionJob = `-- name: CreateConversionJob :one
INSERT INTO conversion_jobs (
    project_id,
    project_file_id
)
SELECT
    project_file.project_id,
    project_file.id
FROM project_files AS project_file
WHERE project_file.project_id = $1
  AND project_file.id = $2
RETURNING
    id,
    project_id,
    project_file_id,
    status,
    attempt_count,
    last_error,
    created_at,
    started_at,
    finished_at,
    updated_at
`

type CreateConversionJobParams struct {
	ProjectID     uuid.UUID
	ProjectFileID uuid.UUID
}

func (q *Queries) CreateConversionJob(ctx context.Context, arg CreateConversionJobParams) (ConversionJob, error) {
	row := q.db.QueryRow(ctx, createConversionJob, arg.ProjectID, arg.ProjectFileID)
	var i ConversionJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectFileID,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversionJobByIDAndProject = `-- name: GetConversionJobByIDAndProject :one
SELECT
    id,
    project_id,
    project_file_id,
    status,
    attempt_count,
    last_error,
    created_at,
    started_at,
    finished_at,
    updated_at
FROM conversion_jobs
WHERE id = $1
  AND project_id = $2
`

type GetConversionJobByIDAndProjectParams struct {
	ConversionJobID uuid.UUID
	ProjectID       uuid.UUID
}

func (q *Queries) GetConversionJobByIDAndProject(ctx context.Context, arg GetConversionJobByIDAndProjectParams) (ConversionJob, error) {
	row := q.db.QueryRow(ctx, getConversionJobByIDAndProject, arg.ConversionJobID, arg.ProjectID)
	var i ConversionJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectFileID,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversionJobsByProjectFile = `-- name: ListConversionJobsByProjectFile :many
SELECT
    id,
    project_id,
    project_file_id,
    status,
    attempt_count,
    last_error,
    created_at,
    started_at,
    finished_at,
    updated_at
FROM conversion_jobs
WHERE project_id = $1
  AND project_file_id = $2
ORDER BY
    created_at DESC,
    id ASC
`

type ListConversionJobsByProjectFileParams struct {
	ProjectID     uuid.UUID
	ProjectFileID uuid.UUID
}

func (q *Queries) ListConversionJobsByProjectFile(ctx context.Context, arg ListConversionJobsByProjectFileParams) ([]ConversionJob, error) {
	rows, err := q.db.Query(ctx, listConversionJobsByProjectFile, arg.ProjectID, arg.ProjectFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversionJob
	for rows.Next() {
		var i ConversionJob
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectFileID,
			&i.Status,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversionJobFailed = `-- name: MarkConversionJobFailed :one
UPDATE conversion_jobs
SET
    status = 'failed',
    finished_at = now(),
    last_error = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'running'
RETURNING
    id,
    project_id,
    project_file_id,
    status,
    attempt_count,
    last_error,
    created_at,
    started_at,
    finished_at,
    updated_at
`

type MarkConversionJobFailedParams struct {
	LastError       *string
	ConversionJobID uuid.UUID
}

func (q *Queries) MarkConversionJobFailed(ctx context.Context, arg MarkConversionJobFailedParams) (ConversionJob, error) {
	row := q.db.QueryRow(ctx, markConversionJobFailed, arg.LastError, arg.ConversionJobID)
	var i ConversionJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectFileID,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markConversionJobSucceeded = `-- name: MarkConversionJobSucceeded :one
UPDATE conversion_jobs
SET
    status = 'succeeded',
    finished_at = now(),
    last_error = NULL,
    updated_at = now()
WHERE id = $1
  AND status = 'running'
RETURNING
    id,
    project_id,
    project_file_id,
    status,
    attempt_count,
    last_error,
    created_at,
    started_at,
    finished_at,
    updated_at
`

func (q *Queries) MarkConversionJobSucceeded(ctx context.Context, conversionJobID uuid.UUID) (ConversionJob, error) {
	row := q.db.QueryRow(ctx, markConversionJobSucceeded, conversionJobID)
	var i ConversionJob
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProjectFileID,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
