// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_storage.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createProjectFile = `-- name: CreateProjectFile :one
INSERT INTO project_files (
    project_id,
    uploaded_by_user_id,
    content_sha256,
    original_filename,
    media_type
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    project_id,
    uploaded_by_user_id,
    content_sha256,
    original_filename,
    media_type,
    created_at
`

type CreateProjectFileParams struct {
	ProjectID        uuid.UUID
	UploadedByUserID uuid.UUID
	ContentSha256    string
	OriginalFilename string
	MediaType        *string
}

func (q *Queries) CreateProjectFile(ctx context.Context, arg CreateProjectFileParams) (ProjectFile, error) {
	row := q.db.QueryRow(ctx, createProjectFile,
		arg.ProjectID,
		arg.UploadedByUserID,
		arg.ContentSha256,
		arg.OriginalFilename,
		arg.MediaType,
	)
	var i ProjectFile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UploadedByUserID,
		&i.ContentSha256,
		&i.OriginalFilename,
		&i.MediaType,
		&i.CreatedAt,
	)
	return i, err
}

const ensureContentObject = `-- name: EnsureContentObject :one
INSERT INTO content_objects (
    sha256,
    size_bytes
)
VALUES (
    $1,
    $2
)
ON CONFLICT (sha256) DO UPDATE
SET
    size_bytes = content_objects.size_bytes
WHERE content_objects.size_bytes = EXCLUDED.size_bytes
RETURNING
    sha256,
    size_bytes,
    created_at
`

type EnsureContentObjectParams struct {
	Sha256    string
	SizeBytes int64
}

func (q *Queries) EnsureContentObject(ctx context.Context, arg EnsureContentObjectParams) (ContentObject, error) {
	row := q.db.QueryRow(ctx, ensureContentObject, arg.Sha256, arg.SizeBytes)
	var i ContentObject
	err := row.Scan(&i.Sha256, &i.SizeBytes, &i.CreatedAt)
	return i, err
}

const getContentObjectBySHA256 = `-- name: GetContentObjectBySHA256 :one
SELECT
    sha256,
    size_bytes,
    created_at
FROM content_objects
WHERE sha256 = $1
`

func (q *Queries) GetContentObjectBySHA256(ctx context.Context, sha256 string) (ContentObject, error) {
	row := q.db.QueryRow(ctx, getContentObjectBySHA256, sha256)
	var i ContentObject
	err := row.Scan(&i.Sha256, &i.SizeBytes, &i.CreatedAt)
	return i, err
}

const getProjectFileByIDAndProject = `-- name: GetProjectFileByIDAndProject :one
SELECT
    id,
    project_id,
    uploaded_by_user_id,
    content_sha256,
    original_filename,
    media_type,
    created_at
FROM project_files
WHERE id = $1
  AND project_id = $2
`

type GetProjectFileByIDAndProjectParams struct {
	ProjectFileID uuid.UUID
	ProjectID     uuid.UUID
}

func (q *Queries) GetProjectFileByIDAndProject(ctx context.Context, arg GetProjectFileByIDAndProjectParams) (ProjectFile, error) {
	row := q.db.QueryRow(ctx, getProjectFileByIDAndProject, arg.ProjectFileID, arg.ProjectID)
	var i ProjectFile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UploadedByUserID,
		&i.ContentSha256,
		&i.OriginalFilename,
		&i.MediaType,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectFilesByProject = `-- name: ListProjectFilesByProject :many
SELECT
    id,
    project_id,
    uploaded_by_user_id,
    content_sha256,
    original_filename,
    media_type,
    created_at
FROM project_files
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProjectFilesByProject(ctx context.Context, projectID uuid.UUID) ([]ProjectFile, error) {
	rows, err := q.db.Query(ctx, listProjectFilesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectFile
	for rows.Next() {
		var i ProjectFile
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UploadedByUserID,
			&i.ContentSha256,
			&i.OriginalFilename,
			&i.MediaType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
