// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLoginCredentialByEmail = `-- name: GetLoginCredentialByEmail :one
SELECT
    users.id,
    users.email,
    users.display_name,
    users.created_at,
    users.updated_at,
    password_credentials.password_hash
FROM users
INNER JOIN password_credentials
    ON password_credentials.user_id = users.id
WHERE lower(users.email) = lower($1)
`

type GetLoginCredentialByEmailRow struct {
	ID           uuid.UUID
	Email        string
	DisplayName  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	PasswordHash string
}

func (q *Queries) GetLoginCredentialByEmail(ctx context.Context, email string) (GetLoginCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getLoginCredentialByEmail, email)
	var i GetLoginCredentialByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}
