// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentObject struct {
	Sha256    string
	SizeBytes int64
	CreatedAt time.Time
}

type ConversionJob struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	ProjectFileID uuid.UUID
	Status        string
	AttemptCount  int32
	LastError     *string
	CreatedAt     time.Time
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	UpdatedAt     time.Time
}

type ConversionJobOutput struct {
	ConversionJobID uuid.UUID
	ContentSha256   string
	MediaType       string
	CreatedAt       time.Time
}

type PasswordCredential struct {
	UserID       uuid.UUID
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Project struct {
	ID          uuid.UUID
	OwnerUserID uuid.UUID
	Name        string
	Description *string
	Visibility  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProjectBranch struct {
	ID             uuid.UUID
	ProjectID      uuid.UUID
	Name           string
	HeadRevisionID pgtype.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ProjectFile struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	UploadedByUserID uuid.UUID
	ContentSha256    string
	OriginalFilename string
	MediaType        *string
	CreatedAt        time.Time
}

type ProjectRevision struct {
	ID                    uuid.UUID
	ProjectID             uuid.UUID
	AuthorUserID          uuid.UUID
	Message               string
	ParentRevisionID      pgtype.UUID
	MergeParentRevisionID pgtype.UUID
	CreatedAt             time.Time
}

type ProjectRevisionFile struct {
	ProjectID     uuid.UUID
	RevisionID    uuid.UUID
	ProjectFileID uuid.UUID
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
