// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_credentials.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createPasswordCredential = `-- name: CreatePasswordCredential :one
INSERT INTO password_credentials (
    user_id,
    password_hash
)
VALUES (
    $1,
    $2
)
RETURNING
    user_id,
    password_hash,
    created_at,
    updated_at
`

type CreatePasswordCredentialParams struct {
	UserID       uuid.UUID
	PasswordHash string
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, createPasswordCredential, arg.UserID, arg.PasswordHash)
	var i PasswordCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordCredentialByUserID = `-- name: GetPasswordCredentialByUserID :one
SELECT
    user_id,
    password_hash,
    created_at,
    updated_at
FROM password_credentials
WHERE user_id = $1
`

func (q *Queries) GetPasswordCredentialByUserID(ctx context.Context, userID uuid.UUID) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialByUserID, userID)
	var i PasswordCredential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
