// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_branches.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceProjectBranchHead = `-- name: AdvanceProjectBranchHead :one
UPDATE project_branches
SET
    head_revision_id = $1,
    updated_at = now()
WHERE id = $2
  AND project_id = $3
  AND head_revision_id IS NOT DISTINCT FROM
      $4
RETURNING
    id,
    project_id,
    name,
    head_revision_id,
    created_at,
    updated_at
`

type AdvanceProjectBranchHeadParams struct {
	NewHeadRevisionID      pgtype.UUID
	BranchID               uuid.UUID
	ProjectID              uuid.UUID
	ExpectedHeadRevisionID pgtype.UUID
}

func (q *Queries) AdvanceProjectBranchHead(ctx context.Context, arg AdvanceProjectBranchHeadParams) (ProjectBranch, error) {
	row := q.db.QueryRow(ctx, advanceProjectBranchHead,
		arg.NewHeadRevisionID,
		arg.BranchID,
		arg.ProjectID,
		arg.ExpectedHeadRevisionID,
	)
	var i ProjectBranch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.HeadRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectBranch = `-- name: CreateProjectBranch :one
INSERT INTO project_branches (
    project_id,
    name
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    project_id,
    name,
    head_revision_id,
    created_at,
    updated_at
`

type CreateProjectBranchParams struct {
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) CreateProjectBranch(ctx context.Context, arg CreateProjectBranchParams) (ProjectBranch, error) {
	row := q.db.QueryRow(ctx, createProjectBranch, arg.ProjectID, arg.Name)
	var i ProjectBranch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.HeadRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectBranchWithHead = `-- name: CreateProjectBranchWithHead :one
INSERT INTO project_branches (
    project_id,
    name,
    head_revision_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    project_id,
    name,
    head_revision_id,
    created_at,
    updated_at
`

type CreateProjectBranchWithHeadParams struct {
	ProjectID      uuid.UUID
	Name           string
	HeadRevisionID pgtype.UUID
}

func (q *Queries) CreateProjectBranchWithHead(ctx context.Context, arg CreateProjectBranchWithHeadParams) (ProjectBranch, error) {
	row := q.db.QueryRow(ctx, createProjectBranchWithHead, arg.ProjectID, arg.Name, arg.HeadRevisionID)
	var i ProjectBranch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.HeadRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBranchByIDAndProject = `-- name: GetProjectBranchByIDAndProject :one
SELECT
    id,
    project_id,
    name,
    head_revision_id,
    created_at,
    updated_at
FROM project_branches
WHERE id = $1
  AND project_id = $2
`

type GetProjectBranchByIDAndProjectParams struct {
	BranchID  uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetProjectBranchByIDAndProject(ctx context.Context, arg GetProjectBranchByIDAndProjectParams) (ProjectBranch, error) {
	row := q.db.QueryRow(ctx, getProjectBranchByIDAndProject, arg.BranchID, arg.ProjectID)
	var i ProjectBranch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.HeadRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectBranchesByProject = `-- name: ListProjectBranchesByProject :many
SELECT
    id,
    project_id,
    name,
    head_revision_id,
    created_at,
    updated_at
FROM project_branches
WHERE project_id = $1
ORDER BY name ASC, id ASC
`

func (q *Queries) ListProjectBranchesByProject(ctx context.Context, projectID uuid.UUID) ([]ProjectBranch, error) {
	rows, err := q.db.Query(ctx, listProjectBranchesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectBranch
	for rows.Next() {
		var i ProjectBranch
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.HeadRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
