// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_revisions.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectRevision = `-- name: CreateProjectRevision :one
INSERT INTO project_revisions (
    project_id,
    author_user_id,
    message,
    parent_revision_id,
    merge_parent_revision_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    project_id,
    author_user_id,
    message,
    parent_revision_id,
    merge_parent_revision_id,
    created_at
`

type CreateProjectRevisionParams struct {
	ProjectID             uuid.UUID
	AuthorUserID          uuid.UUID
	Message               string
	ParentRevisionID      pgtype.UUID
	MergeParentRevisionID pgtype.UUID
}

func (q *Queries) CreateProjectRevision(ctx context.Context, arg CreateProjectRevisionParams) (ProjectRevision, error) {
	row := q.db.QueryRow(ctx, createProjectRevision,
		arg.ProjectID,
		arg.AuthorUserID,
		arg.Message,
		arg.ParentRevisionID,
		arg.MergeParentRevisionID,
	)
	var i ProjectRevision
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AuthorUserID,
		&i.Message,
		&i.ParentRevisionID,
		&i.MergeParentRevisionID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectRevisionByIDAndProject = `-- name: GetProjectRevisionByIDAndProject :one
SELECT
    id,
    project_id,
    author_user_id,
    message,
    parent_revision_id,
    merge_parent_revision_id,
    created_at
FROM project_revisions
WHERE id = $1
  AND project_id = $2
`

type GetProjectRevisionByIDAndProjectParams struct {
	RevisionID uuid.UUID
	ProjectID  uuid.UUID
}

func (q *Queries) GetProjectRevisionByIDAndProject(ctx context.Context, arg GetProjectRevisionByIDAndProjectParams) (ProjectRevision, error) {
	row := q.db.QueryRow(ctx, getProjectRevisionByIDAndProject, arg.RevisionID, arg.ProjectID)
	var i ProjectRevision
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AuthorUserID,
		&i.Message,
		&i.ParentRevisionID,
		&i.MergeParentRevisionID,
		&i.CreatedAt,
	)
	return i, err
}
