// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_branches.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createProjectBranch = `-- name: CreateProjectBranch :one
INSERT INTO project_branches (
    project_id,
    name
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    project_id,
    name,
    head_revision_id,
    created_at,
    updated_at
`

type CreateProjectBranchParams struct {
	ProjectID uuid.UUID
	Name      string
}

func (q *Queries) CreateProjectBranch(ctx context.Context, arg CreateProjectBranchParams) (ProjectBranch, error) {
	row := q.db.QueryRow(ctx, createProjectBranch, arg.ProjectID, arg.Name)
	var i ProjectBranch
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.HeadRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
