// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    owner_user_id,
    name,
    description
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    owner_user_id,
    name,
    description,
    visibility,
    created_at,
    updated_at
`

type CreateProjectParams struct {
	OwnerUserID uuid.UUID
	Name        string
	Description *string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OwnerUserID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT
    id,
    owner_user_id,
    name,
    description,
    visibility,
    created_at,
    updated_at
FROM projects
WHERE owner_user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
