// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdvanceProjectBranchHead(ctx context.Context, arg AdvanceProjectBranchHeadParams) (ProjectBranch, error)
	ClaimNextPendingConversionJob(ctx context.Context) (ConversionJob, error)
	CreateConversionJob(ctx context.Context, arg CreateConversionJobParams) (ConversionJob, error)
	CreateConversionJobOutput(ctx context.Context, arg CreateConversionJobOutputParams) (ConversionJobOutput, error)
	CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) (PasswordCredential, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectBranch(ctx context.Context, arg CreateProjectBranchParams) (ProjectBranch, error)
	CreateProjectBranchWithHead(ctx context.Context, arg CreateProjectBranchWithHeadParams) (ProjectBranch, error)
	CreateProjectFile(ctx context.Context, arg CreateProjectFileParams) (ProjectFile, error)
	CreateProjectRevision(ctx context.Context, arg CreateProjectRevisionParams) (ProjectRevision, error)
	CreateProjectRevisionFile(ctx context.Context, arg CreateProjectRevisionFileParams) (ProjectRevisionFile, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteProjectBranch(ctx context.Context, arg DeleteProjectBranchParams) (int64, error)
	DeleteSession(ctx context.Context, tokenHash []byte) error
	EnsureContentObject(ctx context.Context, arg EnsureContentObjectParams) (ContentObject, error)
	FinalizeProjectRevision(ctx context.Context, arg FinalizeProjectRevisionParams) (int64, error)
	GetActiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetActiveSessionByTokenHashRow, error)
	GetContentObjectBySHA256(ctx context.Context, sha256 string) (ContentObject, error)
	GetConversionJobByIDAndProject(ctx context.Context, arg GetConversionJobByIDAndProjectParams) (ConversionJob, error)
	GetConversionJobOutputByJobID(ctx context.Context, conversionJobID uuid.UUID) (ConversionJobOutput, error)
	GetLatestConversionJobOutputByProjectFile(ctx context.Context, arg GetLatestConversionJobOutputByProjectFileParams) (ConversionJobOutput, error)
	GetLoginCredentialByEmail(ctx context.Context, email string) (GetLoginCredentialByEmailRow, error)
	GetPasswordCredentialByUserID(ctx context.Context, userID uuid.UUID) (PasswordCredential, error)
	GetProjectBranchByIDAndProject(ctx context.Context, arg GetProjectBranchByIDAndProjectParams) (ProjectBranch, error)
	GetProjectByIDAndOwner(ctx context.Context, arg GetProjectByIDAndOwnerParams) (Project, error)
	GetProjectFileByIDAndProject(ctx context.Context, arg GetProjectFileByIDAndProjectParams) (ProjectFile, error)
	GetProjectRevisionByIDAndProject(ctx context.Context, arg GetProjectRevisionByIDAndProjectParams) (ProjectRevision, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListConversionJobsByProjectFile(ctx context.Context, arg ListConversionJobsByProjectFileParams) ([]ConversionJob, error)
	ListProjectBranchesByProject(ctx context.Context, projectID uuid.UUID) ([]ProjectBranch, error)
	ListProjectFilesByProject(ctx context.Context, projectID uuid.UUID) ([]ProjectFile, error)
	ListProjectFilesByRevision(ctx context.Context, arg ListProjectFilesByRevisionParams) ([]ProjectFile, error)
	ListProjectsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Project, error)
	ListReachableProjectRevisionsFromRevision(ctx context.Context, arg ListReachableProjectRevisionsFromRevisionParams) ([]ProjectRevision, error)
	MarkConversionJobFailed(ctx context.Context, arg MarkConversionJobFailedParams) (ConversionJob, error)
	MarkConversionJobSucceeded(ctx context.Context, conversionJobID uuid.UUID) (ConversionJob, error)
	RenameProjectBranch(ctx context.Context, arg RenameProjectBranchParams) (ProjectBranch, error)
	RequeueConversionJob(ctx context.Context, conversionJobID uuid.UUID) (ConversionJob, error)
	RequeueRunningConversionJobs(ctx context.Context) error
	UpdateProjectMetadataByIDAndOwner(ctx context.Context, arg UpdateProjectMetadataByIDAndOwnerParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
